description: !match "~{split('config', 'title' ,' - ')[0]} Live 2D\n~{split('config', 'title' ,' - ')[1]} Live 2D\nThe model is extracted from game with Spine support.\næ¨¡å‹æ¥è‡ªæ¸¸æˆå†…æå–ï¼Œæ”¯æŒSpine\nPlease set your FPS target in Wallpaper Engine > Settings > Performance > FPS\nè¯·åœ¨ Wallpaper Engine > è®¾ç½® > æ€§èƒ½ > FPS ä¸‹è®¾ç½®FPS\n\nLive preview on: https://arknights.halyul.dev/~{var('config', 'link')}\nGithub: https://github.com/Halyul/aklive2d"
localization:
  en-us:
    ui_notice_title: <hr><h4>ğŸ“ Notes</h4><hr>
    ui_notice_set_fps: <span><b>Set FPS target in Settings</b></span>
    ui_notice_github: "Github: https://github.com/Halyul/aklive2d"
    ui_notice_other_operators: "Previews: https://arknights.halyul.dev/"
    ui_notice_version: !match "~{version('<span>Version: ', '</span>')}"
    ui_background_title: <hr><h4>ğŸ–¼ï¸ Background</h4><hr>
    ui_custom_background: Custom Background
    ui_default_background: Default Background
    ui_logo_title: <hr><h4>ğŸ˜ Logo</h4><hr>
    ui_logo_image: Logo Image
    ui_logo_opacity: Logo Opacity
    ui_logo_ratio: Logo Ratio
    ui_operator_logo: Operator Logo
    ui_translate_x: X Axis Position
    ui_translate_y: Y Axis Position
    ui_position_title: <hr><h4>âš ï¸ Posistion</h4><hr>
    ui_position_padding_bottom: Padding Bottom
    ui_position_padding_left: Padding Left
    ui_position_padding_right: Padding Right
    ui_position_padding_top: Padding Top
    ui_voice_title: <hr><h4>ğŸ”ˆVoice</h4><hr>
    ui_voice_lang: Voice Language
    ui_subtitle_title: <hr><h4>ğŸ“‘ Subtitle</h4><hr>
    ui_subtitle_lang: Subtitle Language
    ui_voice_actor_title: <hr><h4>ğŸ—£ï¸ Voice Actor</h4><hr>
  zh-chs:
    ui_notice_title: <hr><h4>ğŸ“ é€šçŸ¥</h4><hr>
    ui_notice_set_fps: <span><b>åœ¨è®¾ç½®ä¸­è®¾å®šFPSç›®æ ‡</b></span>
    ui_notice_github: "Github: https://github.com/Halyul/aklive2d"
    ui_notice_other_operators: "é¢„è§ˆ: https://arknights.halyul.dev/"
    ui_notice_version: !match "~{version('<span>ç‰ˆæœ¬: ', '</span>')}"
    ui_background_title: <hr><h4>ğŸ–¼ï¸ èƒŒæ™¯</h4><hr>
    ui_custom_background: èƒŒæ™¯å›¾ç‰‡
    ui_default_background: é»˜è®¤èƒŒæ™¯
    ui_logo_title: <hr><h4>ğŸ˜ å›¾æ ‡</h4><hr>
    ui_logo_image: å›¾æ ‡å›¾ç‰‡
    ui_logo_opacity: å›¾æ ‡é€æ˜åº¦
    ui_logo_ratio: å›¾æ ‡æ¯”ä¾‹
    ui_operator_logo: å¹²å‘˜å›¾æ ‡
    ui_translate_x: X è½´ä½ç½®
    ui_translate_y: Y è½´ä½ç½®
    ui_position_title: <hr><h4>âš ï¸ ä½ç½®</h4><hr>
    ui_position_padding_bottom: åº•éƒ¨è·ç¦»
    ui_position_padding_left: å·¦éƒ¨è·ç¦»
    ui_position_padding_right: å³éƒ¨è·ç¦»
    ui_position_padding_top: ä¸Šéƒ¨è·ç¦»
    ui_voice_title: <hr><h4>ğŸ”ˆè¯­éŸ³</h4><hr>
    ui_voice_lang: è¯­éŸ³è¯­è¨€
    ui_subtitle_title: <hr><h4>ğŸ“‘ å­—å¹•</h4><hr>
    ui_subtitle_lang: å­—å¹•è¯­è¨€
    ui_voice_actor_title: <hr><h4>ğŸ—£ï¸ å£°ä¼˜</h4><hr>
properties:
  - key: notice_title
    value: 
     text: ui_notice_title
  - key: notice_set_fps
    value: 
     text: ui_notice_set_fps
  - key: notice_github
    value: 
     text: ui_notice_github
  - key: notice_other_operators
    value: 
     text: ui_notice_other_operators
  - key: notice_version
    value: 
     text: ui_notice_version
  - key: logo_title
    value:
      text: ui_logo_title
  - key: logo
    value: 
     text: ui_operator_logo
     type: bool
     value: true
  - key: logoimage
    value: 
     text: ui_logo_image
     type: file
     value: ""
     condition: logo.value == true
  - key: logoratio
    value: 
     text: ui_logo_ratio
     type: "slider"
     value: 61.8
     condition: logo.value == true
     fraction: true
     max: 100
     min: 0
     precision: 2
     step: 0.1
  - key: logoopacity
    value: 
     text: ui_logo_opacity
     type: slider
     value: 30
     condition: logo.value == true
     fraction: false
     max: 100
     min: 0
  - key: logox
    value: 
     text: ui_translate_x
     type: slider
     value: 0
     condition: logo.value == true
     fraction: false
     max: 100
     min: 0
  - key: logoy
    value: 
     text: ui_translate_y
     type: slider
     value: 0
     condition: logo.value == true
     fraction: false
     max: 100
     min: 0
  - key: background_title
    value: 
     text: ui_background_title
  - key: defaultbackground
    value: 
     text: ui_default_background
     type: combo
     value: !match ~{var('assets', "backgrounds")[0]}
     fraction: false
     max: 100
     min: 0
     options: !match ~{var('assets', "backgroundOptions")}
  - key: background
    value: 
     text: ui_custom_background
     type: file
     value: ""
  - key: position
    value: 
     text: ui_position_title
     type: bool
     value: false
  - key: paddingleft
    value: 
     text: ui_position_padding_left
     type: slider
     value: !match ~{var('config', "viewport_left")}
     condition: position.value == true
     fraction: false
     max: 100
     min: -100
  - key: paddingright
    value: 
     text: ui_position_padding_right
     type: slider
     value: !match ~{var('config', "viewport_right")}
     condition: position.value == true
     fraction: false
     max: 100
     min: -100
  - key: paddingtop
    value: 
     text: ui_position_padding_top
     type: slider
     value: !match ~{var('config', "viewport_top")}
     condition: position.value == true
     fraction: false
     max: 100
     min: -100
  - key: paddingbottom
    value: 
     text: ui_position_padding_bottom
     type: slider
     value: !match ~{var('config', "viewport_bottom")}
     condition: position.value == true
     fraction: false
     max: 100
     min: -100