dynchars: dynchars
item_to_download:
  - homebackground/wrapper
  - ui_camp_logo
  - voice.*/extra
  - char_128
  - spritepack/char_portrait.*
additional_regex:
  - ^(?!(avg|charpack))(.*)$
servers:
  - name: cn
    url: https://ak-conf.hypergryph.com/config/prod/official/network_config
